const Constants = {
  channels: {
    WINDOW_POSITION: "window-position",
    SET_WINDOW_POSITION: "set-window-position",
    GET_WINDOW_POSITION: "get-window-position",
    WINDOW_MINIMIZE: "window-minimize",
    WINDOW_MAXIMIZE: "window-maximize",
    WINDOW_UNMAXIMIZE: "window-unmaximize",
    WINDOW_CLOSE: "window-close",
    WINDOW_IS_MAXIMIZED: "window-is-maximized",
    OPEN_DIALOG: "open-dialog",
    WINDOW_BLUR: "window-blur",
    UPDATE: "update",
    SAVE: "save",
    IMAGE_UPLOAD: "image-upload",
    RELOAD_FILES: "reload-files",
    UNDO: "undo",
    REDO: "redo",
    SELECT_ALL: "select-all",
    SHOW_IN_FINDER: "show-in-finder",
    OPEN_SETTINGS: "open-settings",
    USER_CONFIG_UPDATE: "user-config-update",
    TEST: "test",
    OPEN_ONBOARDING: "open-onboarding",
    UPDATE_CONFIG: "update-config",
    CLOSE_ONBOARDING: "close-onboarding",
    WORKSPACE_ACTION: "workspace-action",
  },
};
export default Constants;
