const Constants = {
  channels: {
    OPEN_DIALOG: "open-dialog",
    WINDOW_BLUR: "window-blur",
    UPDATE: "update",
    SAVE: "save",
    IMAGE_UPLOAD: "image-upload",
    RELOAD_FILES: "reload-files",
    UNDO: "undo",
    REDO: "redo",
    SHOW_IN_FINDER: "show-in-finder",
    OPEN_SETTINGS: "open-settings",
    USER_CONFIG_UPDATE: "user-config-update",
    TEST: "test",
    OPEN_ONBOARDING: "open-onboarding",
    UPDATE_CONFIG: "update-config",
    CLOSE_ONBOARDING: "close-onboarding",
    WORKSPACE_ACTION: "workspace-action",
    SAVE_ALBUM: "save-album",
    ADD_TO_ALBUM: "add-to-album",
    REMOVE_FROM_ALBUM: "remove-from-album",
    EDIT_ALBUM: "edit-album",
    DELETE_ALBUM: "delete-album",
    ADD_FOLDER_TO_ALBUM: "add-folder-to-album",
    REMOVE_FOLDER_FROM_ALBUM: "remove-folder-from-album",
  },
};
export default Constants;
