/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoneditorRouteRouteImport } from './routes/_noneditor/route'
import { Route as NoneditorIndexRouteImport } from './routes/_noneditor/index'

const NoneditorRouteRoute = NoneditorRouteRouteImport.update({
  id: '/_noneditor',
  getParentRoute: () => rootRouteImport,
} as any)
const NoneditorIndexRoute = NoneditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoneditorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof NoneditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof NoneditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_noneditor': typeof NoneditorRouteRouteWithChildren
  '/_noneditor/': typeof NoneditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_noneditor' | '/_noneditor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NoneditorRouteRoute: typeof NoneditorRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_noneditor': {
      id: '/_noneditor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NoneditorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_noneditor/': {
      id: '/_noneditor/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NoneditorIndexRouteImport
      parentRoute: typeof NoneditorRouteRoute
    }
  }
}

interface NoneditorRouteRouteChildren {
  NoneditorIndexRoute: typeof NoneditorIndexRoute
}

const NoneditorRouteRouteChildren: NoneditorRouteRouteChildren = {
  NoneditorIndexRoute: NoneditorIndexRoute,
}

const NoneditorRouteRouteWithChildren = NoneditorRouteRoute._addFileChildren(
  NoneditorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  NoneditorRouteRoute: NoneditorRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
